### ISSUE TITLE
Yamux causing problems in production Elastic IPFS deployment

### ISSUE THREAD

**Issue by alanshaw** [ChainSafe/js-libp2p-yamux#23]
We had to revert adding yamux to Elastic IPFS. I need to verify the exact cause and will add the error here - we think the node process is crashing but have not been able to retrieve logs just yet.

Here's our graphs showing recovery after revert:

<img width="1431" alt="Screenshot 2023-02-28 at 14 22 11" src="https://user-images.githubusercontent.com/152863/221885390-824e11f2-6256-4f23-81e7-64d606ba1149.png">

**Comment by alanshaw** [comment]
Might be this unhandled rejection...:

```
[ERR_STREAM_ABORT] stream aborted
CodeError: stream aborted
    at EventTarget.abort (file:///app/node_modules/@chainsafe/libp2p-yamux/dist/src/stream.js:190:20)
    at [nodejs.internal.kHybridDispatch] (node:internal/event_target:731:20)
    at EventTarget.dispatchEvent (node:internal/event_target:673:26)
    at abortSignal (node:internal/abort_controller:308:10)
    at AbortController.abort (node:internal/abort_controller:338:5)
    at YamuxStream.closeWrite (file:///app/node_modules/@chainsafe/libp2p-yamux/dist/src/stream.js:126:30)
    at YamuxStream.close (file:///app/node_modules/@chainsafe/libp2p-yamux/dist/src/stream.js:97:14)
    at file:///app/node_modules/libp2p/dist/src/connection/index.js:80:41
    at Array.forEach (<anonymous>)
    at ConnectionImpl.close (file:///app/node_modules/libp2p/dist/src/connection/index.js:80:26)
```

**Comment by wemeetagain** [comment]
Thanks for reporting. Seems the issue is this Promise rejection not being handled: https://github.com/ChainSafe/js-libp2p-yamux/blob/master/src/stream.ts#L289
Working on a fix now
